config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do
    resources :tickets do
      resources :prices
    end
  end
end

app/models/price.rb
class Price
  include Mongoid::Document
  field :discount_value, type: Float
  field :value, type: Float
  field :benefit_tier, type: String
  belongs_to :ticket
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :name, type: String

  has_many :tickets, dependent: :destroy

  def self.sort_by_biggest_discounts
    ascending = -1

    clookup = [
      {
        '$lookup': {
          'from': "tickets",
          'localField': "_id",
          'foreignField': "product_id",
          'as': "tickets"
        }
      },
      { '$unwind': '$tickets' },
      {
        '$lookup': {
          'from': "prices",
          'localField': "tickets._id",
          'foreignField': "ticket_id",
          'as': "prices"
        }
      },
      { '$unwind': '$prices' },
      {
        '$sort': {
          'prices.discount_value': ascending
        }
      },
      {
        '$group': {
            "_id": "$_id",
            "name": { "$first": "$name" },
            "discount_value": { "$first": "$prices.discount_value" }
        }
      },
      {
        '$sort': {
            'discount_value': ascending
        }
      },
    ].as_json

    docs = where({}).collection.aggregate(clookup)
    ids = docs.map { |doc| doc['_id'] }.uniq
    id_indices = Hash[ids.map.with_index { |id,idx| [id,idx] }]
    Product.find(ids).sort_by { |product| id_indices[product.id] }
  end
end

app/models/ticket.rb
class Ticket
  include Mongoid::Document

  field :label, type: String
  belongs_to :product
  has_many :prices, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_product
  before_action :set_ticket
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = @ticket.prices
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = @ticket.prices.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = @ticket.prices.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to location_after_action, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to location_after_action, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def location_after_action
      product_ticket_prices_path(@product, @ticket)
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_ticket
      @ticket = @product.tickets.find(params[:ticket_id])
    end

    def set_price
      @price = @ticket.prices.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_params
      params.require(:price).permit(:discount_value, :value, :benefit_tier)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.sort_by_biggest_discounts.page(1)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_product
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = @product.tickets
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = @product.tickets.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = @product.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to location_after_action, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to location_after_action, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def location_after_action
      product_tickets_path(@product)
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_ticket
      @ticket = @product.tickets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:label)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMongo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prices/_form.html.erb
<%= form_with(model: price, url: url, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
        <% price.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :discount_value %>
    <%= form.number_field :discount_value %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :benefit_tier %>
    <%= form.text_field :benefit_tier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price, url: product_ticket_price_path(@product, @ticket, @price) %>

<%= link_to 'Back', product_ticket_prices_path(@product, @ticket) %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th>Discount value</th>
      <th>Value</th>
      <th>Benefit tier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.discount_value %></td>
        <td><%= price.value %></td>
        <td><%= price.benefit_tier %></td>
        <td><%= link_to 'Edit', edit_product_ticket_price_path(@product, @ticket, price) %></td>
<!--        <td><%#= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', product_tickets_path(@product) %>
<%= link_to 'New Price', new_product_ticket_price_path(@product, @ticket) %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price, url: product_ticket_prices_path(@product, @ticket) %>

<%= link_to 'Back', product_ticket_prices_path(@product, @ticket) %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discount value:</strong>
  <%= @price.discount_value %>
</p>

<p>
  <strong>Value:</strong>
  <%= @price.value %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @price.ticket_id %>
</p>

<p>
  <strong>Benefit tier:</strong>
  <%= @price.benefit_tier %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tickets %>
    <%= form.text_field :tickets %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tickets</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'tickets', product_tickets_path(product) %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Tickets:</strong>
  <%= @product.tickets %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, url: url, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket, url: product_ticket_path(@product, @ticket) %>

<%= link_to 'Back', product_tickets_path(@product) %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.label %></td>
        <td><%= link_to 'Prices', product_ticket_prices_path(@product, ticket) %></td>
        <td><%= link_to 'Edit', edit_product_ticket_path(@product, ticket) %></td>
<!--        <td><%#= link_to 'Destroy', product_ticket_price_path(@product, ticket), method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', products_path %>
<%= link_to 'New Ticket', new_product_ticket_path(@product) %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket, url: product_tickets_path(@product) %>

<%= link_to 'Back', product_tickets_path(@product) %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @ticket.product_id %>
</p>

<p>
  <strong>Prices:</strong>
  <%= @ticket.prices %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>